const express = require('express')
const cors = require('cors')
require('dotenv').config()
const utilisateurs = require('./routes/utilisateurs.js')
const fournisseurs = require('./routes/fournisseurs.js')
const produits = require('./routes/produits.js')
const clients = require('./routes/cilents.js')
const ventes = require('./routes/ventes.js')
const stats = require('./routes/stats.js')
const app = express()

app.use(cors())
app.use(express.urlencoded({ extended: false }))
app.use(express.json())
app.use('/uploads', express.static('uploads'))

app.use('/api/utilisateurs', utilisateurs)
app.use('/api/fournisseurs', fournisseurs)
app.use('/api/clients', clients)
app.use('/api/produits', produits)
app.use('/api/ventes', ventes)
app.use('/api/stats', stats)
app.listen(5000, () => {
  console.log('app listening on port 5000!')
})
